repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/bandit
    rev: "1.6.2" # Update me!
    hooks:
      - id: bandit
  - repo: https://github.com/prettier/prettier
    rev: "1.19.1"
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
