version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-dnd"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pyirc1a3xve2"
s3_prefix = "sam-dnd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
